@startuml

title
<b>Movies voice assistant pipeline</b>
end title

package Users {
    actor VoiceInterface

}

package ETL {
    [Data ETL]
}

package API {
    [API Gateway]
}

package Storage {
   database SearchStorage
}

package Cache {
    database CacheStorage
}

VoiceInterface --down--> [API Gateway] : voice command

[API Gateway] -left-> CacheStorage : get context from cache

[API Gateway] -right-> SearchStorage : get data from storage

[Data ETL] --down--> SearchStorage : update data

@enduml